sudo: false
before_install:
- echo -n $DLPP > dlpp.txt
install:
- wget https://purrrl-production.s3.amazonaws.com/51/1440033633/stat_dep.tar.xz.gpg
- gpg --passphrase-file dlpp.txt --no-use-agent --batch -o stat_dep.tar.xz --decrypt
  stat_dep.tar.xz.gpg
- xz -d stat_dep.tar.xz
- tar xf stat_dep.tar
- export STATABATCH="stata -b"
- export PATH="$PWD/stata12/:.:$PATH"
script:
- cd src && make build
env:
  global:
    secure: ck0NUXPPbJhLH4G+KzONJh2N5nb8YlJNMBURbGd8Drz8HMFmc+2wOS5wwd/v/9R+n8lo4/lpDCUyC7nvAjSn3p/qs4VMeIytKx40qD620B77lUg9rKbxislbLLOd3h9DRmPJ8M3crbkt/oZQPFbNEsD4jWlikvvO3O2df54xT+8=
